[package]
name = "dbdiff"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
dbconn = { path = "../conn" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
async-trait.workspace = true
tokio = { workspace = true, features = ["full"] }
