//! What each database calls a keyword.
//!
//! A common vocabulary and five short deltas, rather than six lists. That is
//! most of what makes this table-driven: what is particular to a dialect is the
//! only thing written down under its name, so the difference between two of
//! them is readable at a glance — eight words for DuckDB, eighteen for SQL
//! Server.
//!
//! The lists are read out of the databases rather than remembered, which is the
//! only way they stay true across a version bump. Each table records the query
//! that produced it. Two needed a program instead of a query and those are kept
//! as `crates/drivers/duckdb/examples/duckdb-keywords.rs` and its SQLite
//! counterpart, so the tables can
//! be regenerated rather than patched by hand.
//!
//! Every list is sorted, and that is load-bearing rather than tidy: lookup is a
//! binary search over a static slice, so an entry in the wrong place is simply
//! never found. The test at the bottom is what keeps it true.

/// The vocabulary of SQL itself, as every one of these dialects reads it.
///
/// Sourced from `SELECT word, catcode FROM pg_get_keywords()` on PostgreSQL
/// 17.10 — the table Appendix C of the manual is generated from — and then
/// judged, because a keyword table and a highlighter's word list are not the
/// same thing. Every reserved word is here; painting one can never surprise
/// anybody, since the server will not accept it as a bare column name either.
///
/// The unreserved bucket is where the judgement is. It cannot be taken whole:
/// it holds 327 words including `name`, `value`, `level` and `year`, which are
/// unreserved precisely because they are ordinary column names, and an editor
/// that paints `SELECT name, value FROM config` as three keywords is worse than
/// one that paints nothing. Nor can it be dropped: `insert`, `update`, `delete`
/// and `set` are all unreserved, and an editor that does not colour `INSERT` is
/// not colouring SQL. So what is taken is the unreserved words that name a
/// statement, name something a statement acts on, or introduce a clause.
///
/// The cost of that line is real and accepted: a column genuinely called `key`
/// or `type` gets painted, which is a cosmetic surprise on a rare name, against
/// `PRIMARY KEY` and `CREATE TYPE` going unpainted every time they occur.
///
/// PostgreSQL therefore has no table of its own below. It is this one.
pub(crate) const COMMON: &[&str] = &[
    "abort",
    "add",
    "aggregate",
    "all",
    "alter",
    "analyse",
    "analyze",
    "and",
    "any",
    "array",
    "as",
    "asc",
    "asymmetric",
    "authorization",
    "begin",
    "between",
    "bigint",
    "bigserial",
    "binary",
    "bit",
    "boolean",
    "both",
    "by",
    "bytea",
    "call",
    "called",
    "cascade",
    "case",
    "cast",
    "char",
    "character",
    "check",
    "checkpoint",
    "close",
    "cluster",
    "coalesce",
    "collate",
    "collation",
    "column",
    "comment",
    "commit",
    "committed",
    "concurrently",
    "conflict",
    "constraint",
    "copy",
    "create",
    "cross",
    "cube",
    "current_catalog",
    "current_date",
    "current_role",
    "current_schema",
    "current_time",
    "current_timestamp",
    "current_user",
    "cycle",
    "database",
    "date",
    "deallocate",
    "dec",
    "decimal",
    "declare",
    "default",
    "deferrable",
    "deferred",
    "definer",
    "delete",
    "desc",
    "discard",
    "distinct",
    "do",
    "domain",
    "drop",
    "each",
    "else",
    "end",
    "enum",
    "escape",
    "except",
    "exclude",
    "execute",
    "exists",
    "explain",
    "extension",
    "extract",
    "false",
    "fetch",
    "filter",
    "float",
    "following",
    "for",
    "foreign",
    "freeze",
    "from",
    "full",
    "function",
    "generated",
    "grant",
    "greatest",
    "group",
    "grouping",
    "groups",
    "having",
    "identity",
    "if",
    "ilike",
    "immediate",
    "immutable",
    "import",
    "in",
    "include",
    "increment",
    "index",
    "inet",
    "inherits",
    "initially",
    "inner",
    "inout",
    "insert",
    "instead",
    "int",
    "integer",
    "intersect",
    "interval",
    "into",
    "invoker",
    "is",
    "isnull",
    "isolation",
    "join",
    "json",
    "json_array",
    "json_arrayagg",
    "json_exists",
    "json_object",
    "json_objectagg",
    "json_query",
    "json_scalar",
    "json_serialize",
    "json_table",
    "json_value",
    "jsonb",
    "key",
    "language",
    "lateral",
    "leading",
    "leakproof",
    "least",
    "left",
    "like",
    "limit",
    "listen",
    "load",
    "localtime",
    "localtimestamp",
    "lock",
    "materialized",
    "maxvalue",
    "merge_action",
    "minvalue",
    "move",
    "national",
    "natural",
    "nchar",
    "no",
    "none",
    "normalize",
    "not",
    "nothing",
    "notify",
    "notnull",
    "nowait",
    "null",
    "nullif",
    "nulls",
    "numeric",
    "of",
    "off",
    "offset",
    "on",
    "only",
    "operator",
    "or",
    "order",
    "out",
    "outer",
    "over",
    "overlaps",
    "overlay",
    "owned",
    "owner",
    "parallel",
    "partition",
    "placing",
    "policy",
    "position",
    "preceding",
    "precision",
    "prepare",
    "primary",
    "procedure",
    "publication",
    "range",
    "real",
    "reassign",
    "recursive",
    "references",
    "refresh",
    "reindex",
    "release",
    "rename",
    "repeatable",
    "replace",
    "reset",
    "restart",
    "restrict",
    "return",
    "returning",
    "returns",
    "revoke",
    "right",
    "role",
    "rollback",
    "rollup",
    "routine",
    "row",
    "rows",
    "rule",
    "savepoint",
    "schema",
    "security",
    "select",
    "sequence",
    "serial",
    "serializable",
    "server",
    "session_user",
    "set",
    "setof",
    "sets",
    "show",
    "similar",
    "skip",
    "smallint",
    "smallserial",
    "some",
    "sql",
    "stable",
    "start",
    "statistics",
    "stored",
    "strict",
    "subscription",
    "substring",
    "symmetric",
    "system_user",
    "table",
    "tablesample",
    "tablespace",
    "temp",
    "temporary",
    "text",
    "then",
    "ties",
    "time",
    "timestamp",
    "to",
    "trailing",
    "transaction",
    "treat",
    "trigger",
    "trim",
    "true",
    "truncate",
    "type",
    "unbounded",
    "uncommitted",
    "union",
    "unique",
    "unlisten",
    "unlogged",
    "update",
    "user",
    "using",
    "uuid",
    "vacuum",
    "valid",
    "values",
    "varchar",
    "variadic",
    "varying",
    "verbose",
    "view",
    "volatile",
    "when",
    "where",
    "window",
    "with",
    "within",
    "without",
    "wrapper",
    "xmlattributes",
    "xmlconcat",
    "xmlelement",
    "xmlexists",
    "xmlforest",
    "xmlnamespaces",
    "xmlparse",
    "xmlpi",
    "xmlroot",
    "xmlserialize",
    "xmltable",
];

/// What MySQL adds.
///
/// `SELECT WORD FROM INFORMATION_SCHEMA.KEYWORDS WHERE RESERVED = 1` on 8.4,
/// less what is already common.
pub(crate) const MYSQL: &[&str] = &[
    "accessible",
    "asensitive",
    "before",
    "blob",
    "change",
    "condition",
    "continue",
    "convert",
    "cume_dist",
    "cursor",
    "databases",
    "day_hour",
    "day_microsecond",
    "day_minute",
    "day_second",
    "delayed",
    "dense_rank",
    "describe",
    "deterministic",
    "distinctrow",
    "div",
    "double",
    "dual",
    "elseif",
    "empty",
    "enclosed",
    "escaped",
    "exit",
    "first_value",
    "float4",
    "float8",
    "force",
    "fulltext",
    "get",
    "high_priority",
    "hour_microsecond",
    "hour_minute",
    "hour_second",
    "ignore",
    "infile",
    "insensitive",
    "int1",
    "int2",
    "int3",
    "int4",
    "int8",
    "io_after_gtids",
    "io_before_gtids",
    "iterate",
    "keys",
    "kill",
    "lag",
    "last_value",
    "lead",
    "leave",
    "linear",
    "lines",
    "long",
    "longblob",
    "longtext",
    "loop",
    "low_priority",
    "match",
    "mediumblob",
    "mediumint",
    "mediumtext",
    "middleint",
    "minute_microsecond",
    "minute_second",
    "mod",
    "modifies",
    "no_write_to_binlog",
    "nth_value",
    "ntile",
    "optimize",
    "optimizer_costs",
    "option",
    "optionally",
    "outfile",
    "percent_rank",
    "purge",
    "qualify",
    "rank",
    "read",
    "read_write",
    "reads",
    "regexp",
    "repeat",
    "require",
    "resignal",
    "rlike",
    "row_number",
    "schemas",
    "second_microsecond",
    "sensitive",
    "separator",
    "signal",
    "spatial",
    "specific",
    "sql_big_result",
    "sql_calc_found_rows",
    "sql_small_result",
    "sqlexception",
    "sqlstate",
    "sqlwarning",
    "ssl",
    "starting",
    "straight_join",
    "system",
    "terminated",
    "tinyblob",
    "tinyint",
    "tinytext",
    "undo",
    "unlock",
    "unsigned",
    "usage",
    "use",
    "utc_date",
    "utc_time",
    "utc_timestamp",
    "varbinary",
    "varcharacter",
    "virtual",
    "while",
    "write",
    "xor",
    "year_month",
    "zerofill",
];

/// What SQL Server adds.
///
/// SQL Server publishes no catalog view of its keywords, so this was asked of
/// the engine instead: every candidate word was offered as a column name in
/// `CREATE TABLE #probe (<word> int)`, and the ones it refused are reserved.
/// That is what the word means operationally, and unlike a list transcribed
/// from documentation it can be regenerated against a later version.
pub(crate) const MSSQL: &[&str] = &[
    "backup", "continue", "convert", "current", "cursor", "double", "exit", "file", "kill",
    "option", "pivot", "plan", "read", "restore", "top", "unpivot", "use", "while",
];

/// What SQLite adds.
///
/// `sqlite3_keyword_count` and `sqlite3_keyword_name`, which is how SQLite
/// answers this — it has no catalog view for it.
pub(crate) const SQLITE: &[&str] = &[
    "action",
    "after",
    "always",
    "attach",
    "autoincrement",
    "before",
    "current",
    "detach",
    "exclusive",
    "fail",
    "first",
    "glob",
    "ignore",
    "indexed",
    "last",
    "match",
    "others",
    "plan",
    "pragma",
    "query",
    "raise",
    "regexp",
    "virtual",
];

/// What DuckDB adds.
///
/// `SELECT keyword_name FROM duckdb_keywords() WHERE keyword_category =
/// 'reserved'`. Eight words, which is the whole story of DuckDB's relationship
/// to PostgreSQL's grammar: it borrows the language and adds the verbs its own
/// analytical dialect needs.
pub(crate) const DUCKDB: &[&str] = &[
    "describe",
    "lambda",
    "pivot",
    "pivot_longer",
    "pivot_wider",
    "qualify",
    "summarize",
    "unpivot",
];

/// What ClickHouse adds.
///
/// `SELECT keyword FROM system.keywords`, filtered to single words. That table
/// also holds phrases — "add column", "order by" — which a lexer working one
/// token at a time cannot match, and whose parts are covered anyway.
pub(crate) const CLICKHOUSE: &[&str] = &[
    "after",
    "algorithm",
    "alias",
    "allowed_lateness",
    "anti",
    "append",
    "apply",
    "ascending",
    "asof",
    "assume",
    "ast",
    "async",
    "attach",
    "auto_increment",
    "azure",
    "backup",
    "bagexpansion",
    "base_backup",
    "bcrypt_hash",
    "bcrypt_password",
    "bidirectional",
    "change",
    "changeable_in_readonly",
    "changed",
    "cleanup",
    "cluster_host_ids",
    "clusters",
    "cn",
    "codec",
    "columns",
    "compression",
    "const",
    "currentuser",
    "d",
    "data",
    "databases",
    "day",
    "days",
    "dd",
    "deduplicate",
    "descending",
    "describe",
    "detach",
    "dictionaries",
    "dictionary",
    "disk",
    "div",
    "double_sha1_hash",
    "double_sha1_password",
    "empty",
    "enforced",
    "engine",
    "ephemeral",
    "estimate",
    "event",
    "events",
    "every",
    "expression",
    "extended",
    "fields",
    "file",
    "final",
    "first",
    "format",
    "fulltext",
    "global",
    "grantees",
    "granularity",
    "h",
    "hash",
    "hdfs",
    "hh",
    "hierarchical",
    "host",
    "hour",
    "hours",
    "http",
    "id",
    "identified",
    "indexes",
    "indices",
    "inherit",
    "injective",
    "interpolate",
    "invisible",
    "ip",
    "is_object_id",
    "jwt",
    "kerberos",
    "keys",
    "kill",
    "kind",
    "last",
    "layout",
    "ldap",
    "level",
    "lifetime",
    "lightweight",
    "linear",
    "list",
    "live",
    "local",
    "m",
    "match",
    "materialize",
    "max",
    "mcs",
    "memory",
    "merges",
    "metrics",
    "mi",
    "microsecond",
    "microseconds",
    "millisecond",
    "milliseconds",
    "min",
    "minute",
    "minutes",
    "mm",
    "mod",
    "modify",
    "month",
    "months",
    "ms",
    "mutation",
    "n",
    "name",
    "nanosecond",
    "nanoseconds",
    "next",
    "no_password",
    "ns",
    "overridable",
    "part",
    "part_move_to_shard",
    "partial",
    "partitions",
    "paste",
    "permanently",
    "permissive",
    "persistent",
    "pipeline",
    "plaintext_password",
    "plan",
    "populate",
    "prefix",
    "prewhere",
    "profile",
    "projection",
    "protobuf",
    "pull",
    "q",
    "qq",
    "qualify",
    "quarter",
    "quarters",
    "query",
    "quota",
    "randomized",
    "readonly",
    "realm",
    "recompress",
    "regexp",
    "remove",
    "restore",
    "restrictive",
    "resume",
    "s",
    "s3",
    "salt",
    "sample",
    "san",
    "scheme",
    "second",
    "seconds",
    "semi",
    "settings",
    "sha256_hash",
    "sha256_password",
    "signed",
    "simple",
    "source",
    "spatial",
    "sql_tsi_day",
    "sql_tsi_hour",
    "sql_tsi_microsecond",
    "sql_tsi_millisecond",
    "sql_tsi_minute",
    "sql_tsi_month",
    "sql_tsi_nanosecond",
    "sql_tsi_quarter",
    "sql_tsi_second",
    "sql_tsi_week",
    "sql_tsi_year",
    "ss",
    "ssh_key",
    "ssl_certificate",
    "step",
    "storage",
    "strictly_ascending",
    "subpartition",
    "subpartitions",
    "suspend",
    "sync",
    "syntax",
    "system",
    "tables",
    "tag",
    "tags",
    "test",
    "top",
    "totals",
    "ttl",
    "typeof",
    "undrop",
    "unfreeze",
    "unsigned",
    "url",
    "use",
    "visible",
    "watch",
    "watermark",
    "week",
    "weeks",
    "with_itemindex",
    "wk",
    "writable",
    "ww",
    "year",
    "years",
    "yy",
    "yyyy",
    "zkpath",
];

/// Whether `word`, already folded to lower case, is one of `list`.
pub(crate) fn contains(list: &[&str], word: &str) -> bool {
    list.binary_search(&word).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    const TABLES: &[(&str, &[&str])] = &[
        ("COMMON", COMMON),
        ("MYSQL", MYSQL),
        ("MSSQL", MSSQL),
        ("SQLITE", SQLITE),
        ("DUCKDB", DUCKDB),
        ("CLICKHOUSE", CLICKHOUSE),
    ];

    /// Every table is sorted and holds no word twice, because lookup is a
    /// binary search over it.
    ///
    /// The failure this prevents is silent. An entry in the wrong place is not
    /// reported by anything; it simply stops being a keyword, and one word is
    /// left grey in a screen of colour.
    #[test]
    fn every_table_is_sorted_because_lookup_assumes_it() {
        for (name, list) in TABLES {
            let mut sorted = list.to_vec();
            sorted.sort_unstable();
            assert_eq!(*list, sorted.as_slice(), "{name} is out of order");
            assert!(
                list.windows(2).all(|w| w[0] != w[1]),
                "{name} repeats a word"
            );
        }
    }

    /// A dialect's table holds only what is particular to it.
    ///
    /// Not tidiness: a word in both tables is a word whose removal from one of
    /// them changes nothing, so the next person to edit these cannot tell what
    /// is load-bearing.
    #[test]
    fn a_dialect_adds_only_what_the_common_table_lacks() {
        for (name, list) in &TABLES[1..] {
            for word in *list {
                assert!(
                    !contains(COMMON, word),
                    "{name} repeats the common word {word:?}"
                );
            }
        }
    }
}
