[package]
name = "dbffi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
arrow = { workspace = true, features = ["ffi"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
driver-postgres = { path = "../drivers/postgres" }
serde = "1"
serde_json = "1"

[dev-dependencies]
arrow = { workspace = true, features = ["ffi"] }
